[package]
name = "lines_counter"
version = "0.1.0"
authors = ["Ruslan Konovalenko <https://github.com/1ogon1>"]
edition = "2021"

[dependencies]
dirs = "4.0.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }